---
- name: Converge - deploy
  hosts: all:!portainer:!nodered
  connection: local
  gather_facts: no
  become: no
  vars:
    ansible_connection: local
    ansible_shell_type: sh
  tasks:
    - name: Include vars file
      ansible.builtin.include_vars:
        file: "{{ item }}"
      loop:
        - ./vars/main.yml
        - ../../../setup/defaults/main.yml

    - name: Set windows specific docker-compose file
      ansible.builtin.set_fact:
        docker_compose_file: "{{ docker_compose_file_win }}"
      when: "'win-ssh' in group_names or 'winrm' in group_names"

    - name: "Include use - deploy"
      ansible.builtin.include_role:
        name: "use"
        tasks_from: deploy.yml