---
- name: Import default-deploy/prepare
  ansible.builtin.import_playbook: "../default-deploy/node_red/prepare.yml"

- name: Import default-deploy/converge-nodered
  ansible.builtin.import_playbook: "../default-deploy/converge-nodered.yml"

- name: Add undeploy flow
  hosts: nodered
  gather_facts: no
  become: no
  tasks:
    - name: Import undeploy flow
      ansible.builtin.uri:
        url: "http://{{ ansible_host }}:1880/flow"
        method: POST
        body_format: json
        body:
          label: "/undeploy"
          nodes: "{{ lookup('file', '../../../../../undeploy.json' ) | from_json }}"
      register: import_nodered_flow
      failed_when:
        - import_nodered_flow.status != 200
        - "import_nodered_flow.json.message != 'duplicate id'"
      delegate_to: localhost