---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: centos8
    template_name: centos-stream-8
    groups: ['ssh']
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    prepare: ../default-install/converge.yml
    destroy: ../default/destroy.yml
    converge: ../default-uninstall/converge.yml
    verify: ../default-uninstall/verify.yml
verifier:
  name: ansible
