---
- name: Converge - Uninstall
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: "Include docker_portainer - setup"
      ansible.builtin.include_role:
        name: "setup"
        tasks_from: uninstall_portainer.yml

    - name: "Include docker - uninstall"
      ansible.builtin.include_role:
        name: "docker"
        tasks_from: uninstall.yml

